apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: javawebapp
  name: javawebapp-controller
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: javawebapp
    spec:
      containers:
      - image: tutum/hello-world
        name: javawebapp
        ports:
        - name: javawebapp
          containerPort: 80
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: javawebapp
  name: javawebapp
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: http
      targetPort: 80
    - port: 443
      name: https
      targetPort: 80
  selector:
    name: javawebapp
