apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mavenwebapp
spec:
  replicas: 3
  selector:
    matchLabels:
       app: mavenwebapp
  template:
    metadata:
      name: mavenwebappod
      labels:
        app: mavenwebapp
    spec:
      containers:
      - name: mavenwebappcontainer
        image: benadabankah/m-web-app
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /maven-web-application
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /maven-web-application
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 15 
