apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mlops
spec:
  replicas: 3
  selector:
    matchLabels:
       app: mlops
  template:
    metadata:
      name: mlopspod
      labels:
        app: mlops
    spec:
      containers:
      - name: mlopscontainer
        image: benadabankah/ml-repos:latest
        ports:
        - containerPort: 8888
        readinessProbe:
          httpGet:
            path: /
            port: 8888
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /
            port: 8888
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 15


---
# Node Port Service
#run app on <loadbalance>:8888
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mlops
  name: mlops
spec:
  type: LoadBalancer
  ports:
    - port: 8888
      targetPort: 8888
  selector:
     app: mlops
