apiVersion: v1
kind: Pod
metadata:
  name: maven-web-app-10
  labels:
    app: maven-web-app-label-10
spec:
  containers:
  - name: maven-web-app-container-10
    image: benadabankah/m-web-app:latest
    ports:
    - containerPort: 8080
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80



---

apiVersion: v1
kind: Service
metadata:
  name: maven-web-app-service
spec:
  type: NodePort
  selector:
    app: maven-web-app-label-10
  ports:
  - name: maven-app-port
    port: 80 #the services' own port
    targetPort: 8080 #continer's port ( the container inside the pod)
    nodePort: 30100
  - name: nginx-port
    port: 90
    targetPort: 80
    nodePort: 32000
