#kams
apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod # Name of our pod
spec:
  volumes:
  - name: shared-data-logs #creating a shared volume for containers "container-writing-dates" and "container-serving-dates"
    emptyDir: {}   # On node where POD was assigned, this directory will be used for shared volume /var/lib/kubelet/<pod-uid>/volumes
  containers:
  - name: container-writing-dates # Name of the first container
    image: alpine  # Image to use for first container
    command: ["/bin/sh"]
    args: ["-c", "while true; do date >> /var/log/index.html; sleep 10; done"] # write date and output to index.html file every 10 sec
    volumeMounts:
    - name: shared-data-logs
      mountPath: /var/log #Mounting log dir so app can write to it.
  - name: container-serving-dates # Name of second container
    image: nginx:1.19.0 # Image for the second container
    ports:
      - containerPort: 80 # defining what port to use.
    volumeMounts:
    - name: shared-data-logs
      mountPath: /usr/share/nginx/html # where nginx will serve the written file.
