apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx-label
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80


---
apiVersion: v1
kind: Pod
metadata:
  name: dp-website-name
  labels:
    app: dp-website-label
spec:
  containers:
  - name: dp-website
    image: benadabankah/kofi_html_website:v1
    ports:
    - containerPort: 80
