mnemonic: KAMS 
# kind: 
# apiVersion: 
# metadata:
# spec:



kind: Pod
apiVersion: v1
metadata: #information about another data
  name: nginx-kams
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80

---

apiVersion: v1
kind: Pod
metadata: #information about another data
  name: nginx-multi-container-pod
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80

  - name: busybox
    image: busybox
    ports:
    - containerPort: 80




---
#kams
#default is ClusterIP
apiVersion: v1
kind: Service
metadata:
  name: my-datapandas-svc
spec:
  selector:
    app: dp-website-label
  
  ports:
    - protocol: TCP
      port: 80 #service's own port which the services uses to broadcast the information to the world
      targetPort: 80 # containers port . this is the port that the container ( inside the pod) reveals its information

---  
#POD -- running pod
apiVersion: v1
kind: Pod
metadata:
  name: dp-website-name
  labels:
    app: dp-website-label
spec:
  containers:
  - name: dp-website
    image: benadabankah/kofi_html_website:v1
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-datapandas-svc
spec:
  type: NodePort
  selector:
    app: dp-website-label
  ports:
    - protocol: TCP
      port: 80 #service's own port which the services uses to broadcast the information to the world
      targetPort: 80 # containers port . this is the port that the container ( inside the pod) reveals its information

