# Replication Controller
apiVersion: v1
kind: ReplicationController
metadata:
  name: mywebsite-rc
spec:
  replicas: 2
  selector:
    app: mywebsite-label
  template:
    metadata:
      name: mywebsite
      labels:
        app: mywebsite-label
    spec:
      containers:
      - name: nginx-container
        image: benadabankah/ourhttpdwebsite
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: mywebsite-rc-svc
spec:
  type: NodePort
  selector:
    app: mywebsite-label
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30506
