apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: springboot
  name: spring-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: springboot
    spec:
      containers:
      - image: benadabankah/spring-boot-mongo
        name: springboot
        ports:
        - name: springboot
          containerPort: 8080       
---
# Load Balancer Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: springboot
  name: springboot
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    name: springboot
